# =============================================================================
# 00_common.R  —  shared configuration and utility functions
#
# File paths, analysis constants (lag window, event-time window, policy cohorts,
# model covariates) and small helper functions used by the analysis scripts
# (01-04). Source this first.
# =============================================================================

if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman", repos = "https://cloud.r-project.org")
pacman::p_load(data.table, dplyr, tidyr, lubridate, zoo, MatchIt, cobalt,
               fixest, dlnm, splines, MASS, ggplot2, scales)

# ---- paths -------------------------------------------------------------------
DATA_DIR    <- "data"        # simulated inputs (generated by R/00_simulate_data.R)
RESULTS_DIR <- "results"     # all outputs (created on demand)
DERIVED_DIR <- file.path(RESULTS_DIR, "derived")   # intermediate panels
dir.create(DERIVED_DIR, recursive = TRUE, showWarnings = FALSE)

# The DDD model reads the matched daily panel built by R/02_build_matched_panel.R
# from the simulated raw inputs (there is no canonical pre-built panel here, since
# the data are simulated). So run 00 -> 02 before 03 (run_all.R does this).
DDD_PANEL <- file.path(DERIVED_DIR, "matched_daily_panel.csv")

# ---- analysis constants ---------------------
YEARS      <- 2011:2020
PRE_YEARS  <- 2011:2014       # pre-policy window for matching covariate means
MAX_LAG    <- 28L             # distributed-lag window (days)
LAG_DF     <- 3L              # natural-spline df for the lag dimension
REL_WINDOW <- -4:4            # event-time window (relative years)
REF_REL_YEAR <- -1L           # reference relative year (RR standardised to 1)

# Sponge City Development cohorts (treated city administrative codes).
TREAT_2015 <- c(2208, 5109, 3417, 3701, 4501, 3211, 3603, 4106, 3304, 4201, 4307, 3502, 5000)
TREAT_2016 <- c(3100, 5304, 1100, 1200, 6404, 3702, 4403, 4404, 3302, 4602, 6210, 3501, 2102, 6301)
ALL_TREAT  <- c(TREAT_2015, TREAT_2016)
START_2015 <- as.Date("2015-04-15")   # 1st-cohort (2015) synthetic policy start (matches 00_simulate_data.R)
START_2016 <- as.Date("2016-04-15")   # 2nd-cohort (2016) synthetic policy start (matches 00_simulate_data.R)

# Matching covariates (pre-policy means). Mahalanobis 1:1 nearest-neighbour,
# no caliper — this mirrors the matching algorithm used for Supplementary Table S2.
# Because this repository uses synthetic controls, it does not reproduce the real
# matched city pairs or the paper's numerical estimates.
MATCH_COVARIATES <- c("tem_mean", "water_mean", "str_mean", "den_mean")

# Model covariates entered in the DDD (city-year level): GDP, water-supply access
# rate, sewage-treatment rate (str), population density, doctors per capita.
DDD_COVARIATES <- c("gdp", "water", "str", "den", "doc")

# Outcomes analysed by the DDD (total cases + four age groups).
DDD_OUTCOMES <- c("case", "Pre_school", "School", "Adults", "Elders")

# ---- small utilities ---------------------------------------------------------

# Linear interpolation across years within a city (limited extrapolation),
# used to fill gaps in the annual socioeconomic covariates.
safe_interpolate <- function(x, year) {
  if (sum(!is.na(x)) >= 2L) return(zoo::na.approx(x, x = year, rule = 2, na.rm = FALSE))
  x
}
# Forward then backward fill (for residual head/tail gaps after interpolation).
locf_fill <- function(x) zoo::na.locf(zoo::na.locf(x, na.rm = FALSE), fromLast = TRUE)

# Right-aligned moving average over lags 0..k within a city (e.g. 3-day mean).
calc_lag_mean <- function(x, k, group) {
  tmp <- data.table(x = x, group = group)
  tmp[, m := frollmean(x, n = k + 1L, align = "right", na.rm = TRUE), by = group]
  tmp$m
}

# Subset a dlnm crossbasis to a set of rows, preserving its attributes.
subset_crossbasis <- function(cb, keep) {
  structure(cb[keep, , drop = FALSE],
            df = attr(cb, "df"), range = attr(cb, "range"), lag = attr(cb, "lag"),
            argvar = attr(cb, "argvar"), arglag = attr(cb, "arglag"), class = class(cb))
}
# First row of a crosspred matrix as a plain numeric vector.
pred_row <- function(x) if (is.null(dim(x))) as.numeric(x) else as.numeric(x[1, , drop = TRUE])

# Joint Wald chi-square test that a set of model coefficients are all zero
# (used for the parallel-trend and placebo tests).
wald_chisq <- function(model, terms) {
  terms <- intersect(unique(terms), names(stats::coef(model)))
  if (length(terms) == 0L) return(data.table(n_terms = 0L, statistic = NA_real_, df = 0L, p_value = NA_real_))
  b <- stats::coef(model)[terms]
  V <- stats::vcov(model)[terms, terms, drop = FALSE]
  Vinv <- tryCatch(solve(V), error = function(e) MASS::ginv(V))
  stat <- as.numeric(t(b) %*% Vinv %*% b)
  data.table(n_terms = length(terms), statistic = stat, df = length(terms),
             p_value = stats::pchisq(stat, df = length(terms), lower.tail = FALSE))
}
